apiVersion: v1 
kind: Pod 
metadata: 
  name: pod-with-http-healthcheck
spec:
  containers:
  - name: nginx
    image: nginx 
    # defines the health checking
    livenessProbe: 
      # an http probe
      httpGet: 
        path: /_status/healthz
        port: 80
      initialDelaySeconds: 30 
      timeoutSeconds: 1 
    ports: 
    - containerPort: 80 