apiVersion: v1 
kind: Pod 
metadata: 
  name: secret-env-pod
spec:
  containers:
  - name: mycontainer
    image: ubuntu
    command: ['/bin/bash','-c','--']
    args: [ "while true; do sleep 30; done;" ] 
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key:  password
            