apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: ubuntu
    command: ['/bin/bash','-c','--']
    args: [ "while true; do sleep 30; done;" ]
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: mysecret
      defaultMode: 256
      items:
      - key: username
        path: my-group/my-username
        mode: 511
      - key: password
        path: my-group/my-password