apiVersion: v1 
kind: Pod
metadata:
  name: ubuntu-config-test
spec:
  containers:
  - name: ubuntu-test-container
    image: ubuntu
    command: ['/bin/bash']
    envFrom: 
    - configMapRef: 
        name: special-config
  restartPolicy: Never