apiVersion: v1 
kind: Pod
metadata:
  name: ubuntu-config-test
spec:
  containers:
  - name: ubuntu-test-container
    image: ubuntu
    command: ['/bin/bash']
    env: 
      - name: SPECIAL_LEVEL_KEY
        valueFrom:
          configMapKeyRef: 
            name: special-config
            key: special.how
  restartPolicy: Never