apiVersion: v1 
kind: PersistentVolume 
metadata: 
  name: pv0003
spec:
  capacity:
    storage: 5Gi 
  volumeMode: Filesystem 
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow 
  mountOptions:
    - hard 
  nfs:
    path: /var/nfs/general
    server: 10.138.92.234