apiVersion: v1 
kind: Pod 
metadata:
  name: pv-pod-nfs
spec:
  containers:
  - name: pv-pod-nfs
    image: ubuntu 
    command: ['/bin/bash','-c','--']
    args: [ "while true; do sleep 30; done;" ] 
    volumeMounts:
    - mountPath: "/opt/teste"
      name: nfs-volume
  volumes:
  - name: nfs-volume
    persistentVolumeClaim: 
      claimName: pv-nf-claim
